sudo: false
language: python
python:
- '3.6'
install:
- pip install .
- pip install pytest
- pip install docutils
script:
- python setup.py check --restructuredtext -s
- python setup.py test
notifications:
  slack:
    rooms:
      secure: Dpx9stRy9PZWwxUhAUBSdJSCI4Mo26lwWbr9+URnLNJsO8NNr+RwzjMBAvSBDDfNudUWYcfdOfjWvoy1E9x8DEzWE9y74iNOWI41BPQH7k+eM9bZ6xiULneVMrjFZ2AKnFhU/XUdJ1TbNI3x7wPOfL6TGg5ScYj1d74B5abs3Ir7/OzXU7IVC21n/K9I5MSR3fUs7bFKE2aOR24e82x/hvVghSuOaBsfTIlKdojfTZHyMy4fJ1gBScWSh4qwVSbxm9v3SQtpFX83CbIhjxXF25v+qZBOwVVcUf5qIzV/8deszeVGXTaU1yYSiEvEzHksvOujZyzMeVQkooPoM8/bju53tkUldsSjg77T1Fjd0B238OCXT5wTPDyTHHeZSjOjU2P9fAyTR1ajGhnm373sP9rm48COmVxOGIh7r2mMbtHz2sa0F7x6YcfhdUJWFoGorOK/j5l5qK757MuhlaR3kN/cQhn3bj9eIHu9UIJaMk8euPoxhVMcXTs6A9EA+2HJQqLmbNMu/WYV/GRUgJ1sCyOkytjEO32W43OIoabKlJT3s8t8ZWixC3VIPbsf3X5VcYg1ZP0ufnxJlXZJh47hEhuXChwMUEbt1YdXjSwVa8gz6pq+D4mVU4AaXPU1EHOjivddHIPojm+PP4KUfU6Kr3Brl4870SUnqfRRg33A2Co=
